name: Build APK with Buildozer

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential ccache git zip unzip \
          openjdk-17-jdk libstdc++6 zlib1g zlib1g-dev \
          libffi-dev libssl-dev liblzma-dev

        pip install --upgrade pip
        pip install buildozer cython


    - name: Decode keystore from base64
      run: |
        echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 --decode > my-release-key.keystore

    - name: Fix Android SDK license
      run: |
        mkdir -p ~/.android
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/repositories.cfg

    - name: Build APK
      env:
        ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
        # Пароли через secrets:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}
      run: |
        echo "📦 Start building APK..."
        buildozer android release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: bin/*.apk

    - name: Clean previous buildozer output (optional)
      run: rm -rf .buildozer bin

